name: CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Requirements
      run: |
        sudo apt-get update
        sudo apt-get install tree -y
    - uses: ./.github/actions/setup-and-test
      with:
        bin-path: /usr/local/bin

  build-archlinux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Requirements
      run: |
        pacman -Sy tree --noconfirm
    - uses: ./.github/actions/setup-and-test
      with:
        bin-path: /usr/local/bin

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck -y
        
        curl -fsSL https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64 -o shfmt
        chmod +x shfmt
        sudo mv shfmt /usr/local/bin/

    - name: Run ShellCheck
      run: shellcheck -x setup.sh ./scripts/*.sh ./bin/*.sh

    - name: Check Code Formatting
      run: shfmt -d -i 2 -ci .
