name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Requirements
      run: |
        sudo apt-get update
        sudo apt-get install tree shellcheck -y

    - name: Run Setup
      run: |
        ./setup.sh -b /usr/local/bin

    - name: Verify Script Linking
      run: |
        test -f ~/.bashrc
        test -f ~/.bash_aliases
        test -f /usr/local/bin/combine_files.sh

    - name: Test combine_files.sh
      run: |
        ! test -f combined_files.sh
        combine_files.sh sh
        test -f combined_files.sh

    - name: Test Aliases
      run: |
        source ~/.bash_aliases
        shopt -s expand_aliases
        
        ! test -f combined_files.sh
        compyne
        test -f combined_files.py
        
        delete_pycache
        ptree

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck -y
        
        curl -fsSL https://github.com/mvdan/sh/releases/download/v3.7.0/shfmt_v3.7.0_linux_amd64 -o shfmt
        chmod +x shfmt
        sudo mv shfmt /usr/local/bin/

    - name: Run ShellCheck
      run: shellcheck -x setup.sh ./scripts/*.sh ./bin/*.sh

    - name: Check Code Formatting
      run: shfmt -d -i 2 -ci .
